title: Miriam Jayne
author: Miriam Jayne
email: miriam.jayne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A comprehensive description of Miriam Jayne in all her awesomeness

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  miriam1993 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
